name: Weekly CFB Predictions (full run)

on:
  workflow_dispatch:
  push:
    paths:
      - "scripts/**"
      - "requirements.txt"
      - ".github/workflows/main.yml"

permissions:
  contents: write

jobs:
  full-run:
    runs-on: ubuntu-latest
    env:
      PYTHONFAULTHANDLER: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.2.2" "numpy==1.26.4" "pyarrow==16.1.0" "requests>=2.31.0" "scikit-learn>=1.4.0" "joblib>=1.3.0"
          pip install -r requirements.txt || true

      - name: Ensure raw folder exists in repo
        run: |
          mkdir -p data/raw/cfbd
          if [ ! -f data/raw/cfbd/.gitkeep ]; then
            touch data/raw/cfbd/.gitkeep
          fi

      - name: Fetch CFBD data
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          START_SEASON: "2014"
          END_SEASON: "2025"
          INCLUDE_CURRENT: "true"
        run: python -m scripts.fetch_cfbd

      - name: Verify CSVs
        run: |
          ls -lh data/raw/cfbd
          test -f data/raw/cfbd/cfb_schedule.csv

      - name: Build training dataset
        run: python -m scripts.build_dataset

      - name: Train model
        run: python -m scripts.train_model

      - name: Generate predictions
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.predict

      - name: Create website snapshot
        run: python -m scripts.generate_data_snapshot

      - name: Commit raw CSVs and outputs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "🔁 Full run: fetch raw, train, predict, snapshot"
          file_pattern: |
            data/raw/cfbd/*.csv
            data/raw/cfbd/.gitkeep
            docs/data/predictions.json
            docs/data/data_snapshot.json
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"
