name: Build data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: CFBD sanity check (must be 200)
        run: |
          set -euxo pipefail
          if [ -z "${CFBD_API_KEY:-}" ]; then
            echo "CFBD_API_KEY is missing"; exit 2
          fi
          echo "CFBD_API_KEY length: ${#CFBD_API_KEY}"
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ***${CFBD_API_KEY}" \
            "https://api.collegefootballdata.com/teams?year=2025")
          echo "Sanity /teams HTTP ${code}"
          [ "$code" -eq 200 ]

      - name: Fetch team stats
        run: |
          set -euxo pipefail
          python scripts/fetch_team_stats.py --year 2025

      - name: Verify output file (non-empty JSON)
        run: |
          set -euxo pipefail
          test -f docs/data/team_stats.json
          sz=$(wc -c < docs/data/team_stats.json)
          echo "team_stats.json size: $sz bytes"
          # Require at least 10 bytes to avoid committing []
          if [ "$sz" -lt 10 ]; then
            echo "Output looks empty. Failing to avoid committing []."
            exit 3
          fi
          head -n 5 docs/data/team_stats.json || true

      - name: Commit updated data (if changed)
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only stage if the file exists and changed
          if ! git diff --quiet -- docs/data/team_stats.json || \
             ! git ls-files --error-unmatch docs/data/team_stats.json >/dev/null 2>&1; then
            git add docs/data/team_stats.json
            git commit -m "Update team_stats.json"
            git push
          else
            echo "No changes detected in docs/data/team_stats.json"
          fi
