name: Fetch CFBD Data (Commit to Repo)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or ref to commit to (default: current)"
        required: false
        default: ""
  schedule:
    # Daily at 08:00 UTC (adjust if you want)
    - cron: "0 8 * * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    concurrency:
      group: fetch-cfbd-${{ github.ref }}
      cancel-in-progress: false

    env:
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # IMPORTANT: fetch full history so we can commit back cleanly
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure raw data dir
        run: mkdir -p data/raw/cfbd

      - name: Fetch all seasons up to current year
        run: python -m scripts.fetch_cfbd

      - name: Show what changed
        run: |
          echo "Changed files:"
          git status --porcelain
          ls -l data/raw/cfbd || true

      - name: Commit & push raw data
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only the raw data (and any new dirs)
          git add -A data/raw/cfbd

          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            MSG="chore(data): CFBD refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git commit -m "$MSG"
            # Push back to the same branch/ref
            TARGET_REF="${{ github.event.inputs.ref || github.ref_name }}"
            git push origin "HEAD:${TARGET_REF}"
          else
            echo "No changes in data/raw/cfbd; nothing to commit."
          fi
