# .github/workflows/fetch_data.yml

name: 'Manual Fetch and Cache Data'

on:
  # Run this manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Restore Raw Data Cache
        id: cache-raw-data
        uses: actions/cache@v4
        with:
          path: data/raw/cfbd
          key: ${{ runner.os }}-raw-cfbd-data-v1

      - name: 5. Fetch Latest Data from API
        # Only run if the cache is empty (first run or cache bust)
        if: steps.cache-raw-data.outputs.cache-hit != 'true'
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.fetch_cfbd

      - name: 6. Commit and Push Raw Data
        # This step writes updated raw data and snapshot back to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "⬇️ CFBD raw data refresh"
          file_pattern: "data/raw/cfbd/* docs/data/fetch_snapshot.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"
