# .github/workflows/fetch_data.yml

name: 'Manual Fetch and Cache Data'

on:
  # This makes it a manually triggered workflow
  workflow_dispatch:

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Cache Raw Data
        id: cache-raw-data
        uses: actions/cache@v4
        with:
          path: data/raw/cfbd
          key: ${{ runner.os }}-raw-cfbd-data-v1

      - name: 5. Fetch Latest Data from API
        # We run this step only if the cache didn't already exist
        if: steps.cache-raw-data.outputs.cache-hit != 'true'
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.fetch_cfbd
