name: Manual Fetch and Commit CFBD Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (pinned core + project)
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.2.2" "numpy==1.26.4" "pyarrow==16.1.0" "requests>=2.31.0"
          pip install -r requirements.txt || true

      - name: Ensure raw folder exists
        run: mkdir -p data/raw/cfbd && touch data/raw/cfbd/.gitkeep

      - name: Fetch CFBD data (API only)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          START_SEASON: "2014"
          END_SEASON: "2025"
          INCLUDE_CURRENT: "true"
        run: python -m scripts.fetch_cfbd

      - name: Verify CSVs exist
        run: |
          ls -lh data/raw/cfbd || true
          test -f data/raw/cfbd/cfb_schedule.csv

      - name: Commit raw CSVs into repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "⬇️ CFBD raw data refresh (commit CSVs for pipeline)"
          file_pattern: |
            data/raw/cfbd/*.csv
            data/raw/cfbd/.gitkeep
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"
