name: Fetch Team Stats

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Season year to fetch (e.g., 2025)"
        required: true
        default: "2025"

jobs:
  fetch-team-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push the updated JSON back to the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install cfbd

      - name: Run fetch script
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          python scripts/fetch_team_stats.py --year "${{ github.event.inputs.year }}"

      - name: Commit updated data
        run: |
          if git diff --quiet docs/data/team_stats.json; then
            echo "No changes in docs/data/team_stats.json"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/data/team_stats.json
            git commit -m "Update team_stats.json for ${{ github.event.inputs.year }}"
            git push
          fi
