name: 'Manual Fetch and Save Data'

on:
  # This makes it a manually triggered workflow
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Fetch Latest Data from API
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.fetch_cfbd

      - name: 5. Save Data as an Artifact
        # This step packages the downloaded data for other workflows to use.
        uses: actions/upload-artifact@v4
        with:
          name: raw-cfbd-data
          path: data/raw/cfbd
