name: Fetch Team Stats (CFBD)

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Season year"
        required: true
        default: "2025"
  schedule:
    - cron: "7 9 * * 5"  # Fridays 09:07 UTC, adjust as you like

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      YEAR: ${{ github.event.inputs.year || '2025' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      # --- The problem was here: header was '***'
      - name: Sanity check CFBD key (teams endpoint)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          set -euxo pipefail
          # Show only length; never echo the token
          echo "CFBD_API_KEY length: ${#CFBD_API_KEY}"
          # Must include 'Bearer ' prefix in the Authorization header
          code=$(curl -s -o /dev/null -w '%{http_code}' \
            -H "Authorization: Bearer ${CFBD_API_KEY}" \
            "https://api.collegefootballdata.com/teams?year=${YEAR}")
          echo "Sanity /teams HTTP ${code}"
          [ "$code" -eq 200 ]

      - name: Run fetch_team_stats.py
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          set -euxo pipefail
          python scripts/fetch_team_stats.py --year "${YEAR}"

      - name: Show resulting JSON (size + head)
        run: |
          set -euxo pipefail
          mkdir -p docs/data
          : > /dev/null
          echo "Resulting file size:"
          wc -c docs/data/team_stats.json || true
          echo "Preview:"
          head -n 50 docs/data/team_stats.json || true

      - name: Commit docs/data/team_stats.json if changed
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only add if it exists
          if [ -f docs/data/team_stats.json ]; then
            git add docs/data/team_stats.json
          fi

          if ! git diff --cached --quiet; then
            git commit -m "Update team_stats.json for ${YEAR}"
            git push
          else
            echo "No changes to commit."
          fi
