name: Fetch Team Stats

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Season year to fetch (e.g., 2025)"
        required: true
        default: "2025"

jobs:
  fetch-team-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install cfbd

      - name: Pre-flight debug
        run: |
          set -euxo pipefail
          python --version
          pip show cfbd || true
          mkdir -p docs/data docs/input
          echo "Repo root:"
          ls -la
          echo "docs/:"
          ls -la docs || true
          echo "docs/input/:"
          ls -la docs/input || true
          echo "First 40 lines of docs/input/games.txt (if present):"
          head -n 40 docs/input/games.txt || true

      - name: Fetch CFBD team stats
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          set -euxo pipefail
          # Show whether the env var is present (masked)
          if [ -z "${CFBD_API_KEY:-}" ]; then
            echo "::error::CFBD_API_KEY secret is NOT available to this job."
          else
            echo "CFBD_API_KEY length: ${#CFBD_API_KEY}"
          fi

          # Run the script (will fail fast if API key truly missing)
          python scripts/fetch_team_stats.py --year "${{ github.event.inputs.year }}" || {
            echo "::warning::fetch_team_stats.py exited non-zero. Continuing to capture diagnostics."
          }

      - name: Guarantee team_stats.json exists (avoid first-run git errors)
        run: |
          set -euxo pipefail
          mkdir -p docs/data
          if [ ! -f docs/data/team_stats.json ]; then
            echo "::warning::docs/data/team_stats.json was not created by the script. Writing an empty array so the workflow can proceed. Check earlier logs for why (401s, missing games.txt, etc.)."
            echo "[]" > docs/data/team_stats.json
          fi
          echo "Resulting file size:"
          wc -c docs/data/team_stats.json || true
          echo "Preview:"
          head -n 50 docs/data/team_stats.json || true

      - name: Commit updated data
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # If it's not tracked yet, add it
          if ! git ls-files --error-unmatch docs/data/team_stats.json > /dev/null 2>&1; then
            echo "Adding team_stats.json (first run)"
            git add docs/data/team_stats.json
            git commit -m "Add team_stats.json (first run for ${{ github.event.inputs.year }})"
            git push
            exit 0
          fi

          # If tracked, only commit when changed
          if git diff --quiet -- docs/data/team_stats.json; then
            echo "No changes detected in docs/data/team_stats.json"
          else
            git add docs/data/team_stats.json
            git commit -m "Update team_stats.json for ${{ github.event.inputs.year }}"
            git push
          fi
