name: 'Manual Fetch and Cache Data'

on:
  # This makes it a manually triggered workflow that you can run from the Actions tab
  workflow_dispatch:

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Fetch Latest Data from API
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.fetch_cfbd

      - name: 5. Save Data to Cache
        # This step saves the downloaded data folder for the other workflow to use.
        uses: actions/cache/save@v4
        with:
          path: data/raw/cfbd
          # We're using 'v2' as the key version to ensure a fresh start.
          key: ${{ runner.os }}-raw-cfbd-data-v2

