name: Manual Fetch and Cache Datag

on:
  workflow_dispatch:

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.2.2" "numpy==1.26.4" "pyarrow==16.1.0" "requests>=2.31.0"
          pip install -r requirements.txt || true

      - name: 4. Fetch Latest Data from CFBD API (final/completed games only)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          START_SEASON: "2014"
          END_SEASON: "2025"
          INCLUDE_CURRENT: "true"
        run: python -m scripts.fetch_cfbd

      - name: 5. Save Data to Cache
        uses: actions/cache/save@v4
        with:
          path: data/raw/cfbd
          key: ${{ runner.os }}-raw-cfbd-data-v2

      - name: 6. Show sample rows (sanity check)
        run: |
          python - << 'PY'
          import pandas as pd, os
          p = "data/raw/cfbd/cfb_schedule.csv"
          assert os.path.exists(p), f"missing {p}"
          df = pd.read_csv(p, low_memory=False)
          labeled = ((pd.to_numeric(df["home_points"], errors="coerce").notna()) &
                     (pd.to_numeric(df["away_points"], errors="coerce").notna())).sum()
          print("Columns:", df.columns.tolist())
          print("Rows:", len(df), "Labeled:", labeled)
          print(df.head(10).to_string(index=False))
          PY
