name: Manual Fetch and Cache Data

on:
  workflow_dispatch:   # <-- gives you the "Run workflow" button in Actions tab

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.2.2" "numpy==1.26.4" "pyarrow==16.1.0" "requests>=2.31.0"
          pip install -r requirements.txt || true

      - name: Fetch Latest Data from API
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          START_SEASON: "2014"
          END_SEASON: "2025"
          INCLUDE_CURRENT: "true"
        run: python -m scripts.fetch_cfbd

      - name: Save Data to Cache
        uses: actions/cache/save@v4
        with:
          path: data/raw/cfbd
          key: ${{ runner.os }}-raw-cfbd-data-v2
