# .github/workflows/main.yml (FAST DEBUG & PRODUCTION WORKFLOW)

name: Generate Weekly Football Predictions

on:
  workflow_dispatch:
  push:

jobs:
  run-prediction-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Restore Raw Data from Cache
        # This step retrieves the data downloaded by the other workflow.
        uses: actions/cache/restore@v4
        with:
          path: data/raw/cfbd
          # This key MUST match the key in the fetch-data workflow
          key: ${{ runner.os }}-raw-cfbd-data-v2
          restore-keys: |
            ${{ runner.os }}-raw-cfbd-data-

      - name: 5. Build Training Dataset
        run: python -m scripts.build_dataset

      - name: 6. Train Prediction Model
        run: python -m scripts.train_model

      - name: 7. Generate New Predictions
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.predict

      - name: 8. Generate Data Snapshot for Website
        run: python -m scripts.generate_data_snapshot

      - name: 9. Commit and Push Results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "📊 Update weekly predictions & data snapshot"
          file_pattern: "docs/data/predictions.json docs/data/data_snapshot.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"

