# .github/workflows/predict.yml
name: predict

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**"
      - "docs/input/**"
      - ".github/workflows/predict.yml"

permissions:
  contents: write

concurrency:
  group: predict
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/requirements.txt

      - name: Fetch CFBD data (optional)
        run: |
          if [ -f scripts/fetch_cfbd.py ]; then
            python scripts/fetch_cfbd.py || echo "[WARN] fetch_cfbd failed"
          fi

      # NEW split pipeline
      - name: Build dataset
        run: python scripts/build_dataset.py

      - name: Train model
        run: python scripts/train_model.py

      - name: Predict picks
        run: python scripts/predict.py

      - name: Build spreads (market lines)
        run: python scripts/build_spreads.py || echo "[WARN] spreads step failed"

      - name: Build team summaries (cards)
        run: python scripts/make_team_cards.py || echo "[WARN] cards step failed"

      - name: Build team colors
        run: python scripts/build_team_colors.py || echo "[WARN] colors step failed"

      - name: Commit artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add docs/data/predictions.json || true
          git add docs/data/spreads.json || true
          git add docs/data/team_summaries.json || true
          git add docs/data/team_colors.json || true
          git add docs/data/train_meta.json || true
          git add docs/data/train_metrics.json || true
          if ! git diff --cached --quiet; then
            git commit -m "Update predictions & artifacts [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
