# .github/workflows/predict.yml

name: CFB Model Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
      - master
    paths:
      - 'scripts/**'
      - 'docs/input/**'
      - '.github/workflows/predict.yml'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements.txt'
      
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      
      - name: Build dataset
        run: python -m scripts.build_dataset
        working-directory: ./
      
      - name: Train model
        run: python -m scripts.train_model
        working-directory: ./
        
      - name: Predict
        run: python -m scripts.predict
        working-directory: ./
        
      - name: Commit and push artifacts
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/derived/ docs/data/
          # Commit the changes if there are any
          if ! git diff --staged --quiet; then
            git commit -m "CI: Update model and predictions"
            
            # --- THIS IS THE FINAL FIX ---
            # Create/update a dedicated branch for the bot's predictions
            # and force-push to it. This avoids all conflicts with the main branch.
            git branch -M bot/predictions
            git push --force origin bot/predictions
            # --- END OF FIX ---
          else
            echo "No changes to commit."
          fi
