name: Train and Publish Predictions

on:
  workflow_dispatch:     # manual "Run workflow" button
  schedule:
    - cron: "0 * * * *"  # hourly (UTC)
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'docs/input/**'
      - '.github/workflows/predict.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Train and predict
        run: |
          python scripts/train_and_predict.py

      # Instead of pushing to main (which causes conflicts), we create a PR
      - name: Create/update PR with predictions
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update predictions [skip ci]"
          title: "Update predictions"
          body: "Automated update of docs/data/predictions.json"
          branch: "bot/predictions"
          add-paths: |
            docs/data/predictions.json
          delete-branch: true
