name: Train and Publish Predictions

on:
  workflow_dispatch:     # lets you click "Run workflow" manually in Actions tab
  schedule:
    - cron: "0 * * * *"  # runs hourly (UTC)
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'docs/input/**'
      - '.github/workflows/predict.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Train and predict
        run: |
          python scripts/train_and_predict.py

      - name: Commit predictions if changed (rebase-safe)
        run: |
          set -e

          # Bot identity
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Make sure we have the latest remote refs
          git fetch origin main
          git checkout main

          # Stage the output file
          git add docs/data/predictions.json

          # If nothing changed, exit early
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # Commit first so we don't have unstaged changes blocking rebase
          git commit -m "Update predictions [skip ci]"

          # Rebase our new commit on top of the latest main
          git -c rebase.autoStash=true pull --rebase origin main

          # Push. If a race still happens, rebase once more and retry.
          if ! git push origin HEAD:main; then
            echo "Push rejected (non-fast-forward). Rebasing and retrying once..."
            git -c rebase.autoStash=true pull --rebase origin main
            git push origin HEAD:main
          fi
