name: Build Model and Predict (Commit outputs)

on:
  workflow_dispatch:
    inputs:
      week:
        description: "CFB week number (use 0 for hypothetical)"
        required: true
        default: "0"

permissions:
  contents: write

concurrency:
  group: predict
  cancel-in-progress: false

jobs:
  build-and-predict:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout MAIN branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Show input slate for debugging
        run: |
          echo "=== docs/input/games.txt ==="; nl -ba docs/input/games.txt || true
          echo "HEAD: $(git rev-parse --short HEAD)"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ensure package layout for relative imports
      - name: Ensure Python package init files exist
        run: |
          mkdir -p scripts/lib
          touch scripts/__init__.py
          touch scripts/lib/__init__.py

      # >>> IMPORTANT: blow away stale outputs so the script MUST rewrite them
      - name: Pre-clean previous outputs
        run: |
          rm -f docs/data/predictions.json docs/data/debug_predict.json || true

      - name: Build model & predict
        env:
          WEEK: ${{ inputs.week }}
        run: |
          set -euo pipefail
          python -m scripts.predict \
            --input-file docs/input/games.txt \
            --week "${WEEK}" \
            --out-dir docs/data

          test -s docs/data/predictions.json || (echo "ERROR: predictions.json not created" && exit 1)

          echo "=== first 60 lines of predictions.json ==="
          head -n 60 docs/data/predictions.json || true

      # Hard guardrails: must include NEW teams and must NOT include OLD teams
      - name: Verify new slate present / old slate absent
        run: |
          set -euo pipefail
          echo "Checking for this week's teams..."
          grep -qE "Oklahoma|Memphis|Vanderbilt|Iowa State|Washington|Iowa|Fresno State|Cincinnati|LSU|South Dakota State" docs/data/predictions.json \
            || (echo "New slate not found in predictions.json" && exit 1)
          echo "Ensuring last week's telltales are gone..."
          if grep -qE "Duke|Georgia Tech|Vanderbilt\".*,\\s*\"away_team\": \"LSU" docs/data/predictions.json; then
            echo "Old slate still present; failing."
            exit 1
          fi
          echo "Verification OK."

      - name: Commit outputs (safe push)
        run: |
          set -euo pipefail
          git add docs/data/*.json || true
          date -u +"%Y-%m-%dT%H:%M:%SZ" > docs/data/build-stamp.txt
          git add docs/data/build-stamp.txt
          git commit -m "chore(pred): week=${{ inputs.week }} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || git commit --allow-empty -m "chore(pred): timestamp only"
          git pull --rebase origin main || true
          git push origin HEAD:main

      - name: Final verify
        run: |
          git show --name-only --oneline -1