name: predict

on:
  workflow_dispatch:
  schedule:
    # Hourly (UTC). GitHub Actions uses UTC; 0 * * * * ≈ hourly in Chicago too.
    - cron: "0 * * * *"
  push:
    branches: [ "main" ]
    # Only re-run on code/input/workflow changes (not on data outputs)
    paths:
      - "scripts/**"
      - "docs/input/**"
      - ".github/workflows/predict.yml"

# Needed so the workflow can push updated JSON artifacts back to the repo
permissions:
  contents: write

# Avoid overlapping runs that could race on committing artifacts
concurrency:
  group: predict
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # safer rebase/push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/requirements.txt

      # Optional but recommended: fetch/refresh CFBD CSVs used by training & color builder
      - name: Fetch CFBD data
        run: |
          if [ -f scripts/fetch_cfbd.py ]; then
            python scripts/fetch_cfbd.py || echo "[WARN] fetch_cfbd failed; training may fall back to snapshot URLs."
          else
            echo "[INFO] scripts/fetch_cfbd.py not found; using snapshot URLs in train script."
          fi

      - name: Train & predict
        run: |
          python scripts/train_and_predict.py

      - name: Build spreads (market lines)
        run: |
          python scripts/build_spreads.py

      - name: Build team summaries (cards)
        run: |
          python scripts/make_team_cards.py

      - name: Build team colors
        run: |
          python scripts/build_team_colors.py

      - name: Commit artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Rebase to avoid non-fast-forward errors if main moved
          git pull --rebase origin main || true

          git add docs/data/predictions.json || true
          git add docs/data/spreads.json || true
          git add docs/data/team_summaries.json || true
          git add docs/data/team_colors.json || true

          # Commit only if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Update predictions, spreads, team cards & colors [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
