# .github/workflows/main.yml

name: Generate Weekly Football Predictions

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs automatically every Tuesday at 12:00 PM UTC
  schedule:
    - cron: '0 12 * * 2'

  # Runs automatically whenever you push a change to the input games file
  push:
    paths:
      - 'docs/input/games.txt'

jobs:
  run-prediction-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Cache pip dependencies to speed up future runs

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Fetch Latest Data from API
        # This 'env' block securely gives your API key to the fetch script.
        # The key is pulled from the GitHub Secret you created.
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.fetch_cfbd

      - name: 5. Build Training Dataset
        run: python -m scripts.build_dataset

      - name: 6. Train Prediction Model
        run: python -m scripts.train_model

      - name: 7. Generate New Predictions
        # The prediction script also needs the key for the latest schedule/stat context.
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.predict

      - name: 8. Commit and Push Predictions
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Update weekly predictions"
          # Add any other files that your scripts generate and need to be saved.
          file_pattern: "docs/data/predictions.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"
