# .github/workflows/main.yml

name: Generate Weekly Football Predictions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2'
  push:
    paths:
      - 'docs/input/games.txt'

jobs:
  run-prediction-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Cache Raw Data
        # This step saves the downloaded data to speed up future runs.
        id: cache-raw-data
        uses: actions/cache@v4
        with:
          path: data/raw/cfbd
          # The key identifies the cache. Change 'v1' to 'v2' if you ever
          # want to force a full re-download of all historical data.
          key: ${{ runner.os }}-raw-cfbd-data-v1

      - name: 5. Fetch Latest Data from API
        # This step now ONLY runs if the cache was not found.
        if: steps.cache-raw-data.outputs.cache-hit != 'true'
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.fetch_cfbd

      - name: 6. Build Training Dataset
        run: python -m scripts.build_dataset

      - name: 7. Train Prediction Model
        run: python -m scripts.train_model

      - name: 8. Generate New Predictions
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python -m scripts.predict

      - name: 9. Commit and Push Predictions
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Update weekly predictions"
          file_pattern: "docs/data/predictions.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"
