name: Train and Publish Predictions

on:
  workflow_dispatch:     # 👈 adds a manual "Run workflow" button
  schedule:
    - cron: "0 * * * *"  # runs hourly (top of every hour, UTC)
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'docs/input/**'
      - '.github/workflows/predict.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Train and predict
        run: |
          python scripts/train_and_predict.py

      - name: Commit predictions if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/predictions.json
          if ! git diff --cached --quiet; then
            git commit -m "Update predictions [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
