name: Build Model and Predict (Commit outputs)

on:
  workflow_dispatch:
    inputs:
      week:
        description: "CFB week number (use 0 for hypothetical)"
        required: true
        default: "0"

permissions:
  contents: write

concurrency:
  group: predict
  cancel-in-progress: false

jobs:
  build-and-predict:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout MAIN branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Show input slate for debugging
        run: |
          echo "=== docs/input/games.txt ==="
          cat docs/input/games.txt || true
          echo "============================="
          echo "Current HEAD:"
          git rev-parse --short HEAD

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- FIX: ensure __init__.py exists so imports work ---
      - name: Ensure Python package init files exist
        run: |
          mkdir -p scripts/lib
          touch scripts/__init__.py
          touch scripts/lib/__init__.py
          echo "Package inits created"

      - name: Build model & predict (fixed import)
        env:
          WEEK: ${{ inputs.week }}
        run: |
          set -euo pipefail
          python -m scripts.predict \
            --input-file docs/input/games.txt \
            --week "${WEEK}" \
            --out-dir docs/data

          # Sanity check
          test -s docs/data/predictions.json || (echo "ERROR: predictions.json not created" && exit 1)

          echo "=== first 40 lines of predictions.json ==="
          head -n 40 docs/data/predictions.json || true

      - name: Commit outputs (safe push)
        run: |
          set -euo pipefail
          git add docs/data/*.json || true
          date -u +"%Y-%m-%dT%H:%M:%SZ" > docs/data/build-stamp.txt
          git add docs/data/build-stamp.txt
          git commit -m "chore(pred): week=${{ inputs.week }} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || git commit --allow-empty -m "chore(pred): rebuild timestamp only"
          git pull --rebase origin main || true
          git push origin HEAD:main

      - name: Verify output
        run: |
          echo "=== recently committed files ==="
          git show --name-only --oneline -1
          echo "=== teams found in predictions.json ==="
          grep -E "Oklahoma|Memphis|Vanderbilt|Iowa State|Washington|Iowa|Fresno State|Cincinnati|LSU|South Dakota State" -n docs/data/predictions.json || true