name: predict

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**"
      - "docs/input/**"
      - ".github/workflows/predict.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/requirements.txt

      - name: Train & predict
        run: |
          python scripts/train_and_predict.py

      - name: Build spreads (market lines)
        run: |
          python scripts/build_spreads.py

      - name: Build team summaries (cards)
        run: |
          python scripts/make_team_cards.py

      - name: Commit artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Rebase to avoid conflicts
          git pull --rebase origin main || true

          git add docs/data/predictions.json docs/data/spreads.json docs/data/team_summaries.json || true
          git commit -m "Update predictions, spreads & team cards [skip ci]" || echo "No changes to commit"

          git push origin HEAD:main
